[oracle@instance-20210914-dr ~]$ cat sequence_gap.sql
set head off
set feed off
set long 90000
set echo off
set pages 0
spool sequence_gap.log
select (p.SEQUENCE# - s.SEQUENCE#)
from
(SELECT THREAD# ,SEQUENCE#,COMPLETION_TIME FROM V$ARCHIVED_LOG@db_link WHERE DEST_ID=1 and (THREAD#,SEQUENCE# ) IN (SELECT THREAD#,MAX(SEQUENCE#) FROM V$ARCHIVED_LOG@db_link GROUP BY THREAD#)) p,
(SELECT THREAD# ,SEQUENCE#,COMPLETION_TIME FROM V$ARCHIVED_LOG WHERE (THREAD#,SEQUENCE# ) IN (SELECT THREAD#,MAX(SEQUENCE#) FROM V$ARCHIVED_LOG WHERE APPLIED='YES' GROUP BY THREAD#)) s
where p.THREAD#=s.THREAD#
and (p.COMPLETION_TIME - s.COMPLETION_TIME)*24*60 > 20;
spool off

